name: Docker Image CI

on:
  push:
    branches: [ "main" ] ## trigger on main banch push
    tags:
     - 'v*' ## trigger on version tagging, current naming convention for the docker image version release

jobs:

  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        image_name: ['cf-tunnel-pi'] ## Application Name / Folder Name
        platform: ['linux/arm/v7'] ## for now will build on armhf architecture

    steps:
    - name: Checkout New Image
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug

    - name: Build and Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: | 
        TAG=$(echo "${GITHUB_REF#refs/tags/}" | sed 's|refs/heads/||')
        IMAGE=${DOCKER_USERNAME}/${{ matrix.image_name}}
        PLATFORM=${{ matrix.platform }}

        docker buildx build \
          --platform $PLATFORM \
          -t $IMAGE:$TAG \
          -t $IMAGE:latest \
          -f ./${{ matrix.image_name }}/Dockerfile \
          ./${{ matrix.image_name }} \
          --push
